import mongoose from "mongoose";

const schema=new mongoose.Schema({
shippingInfo:{
    hNo:{
        type:String,
        required:true,
    },
    city:{
        type:String,
        required:true,
    },
    state:{
        type:String,
        required:true,
    },
    country:{
        type:String,
        required:true,
    },
    pincode:{
        type:Number,
        required:true,
    },
    contactNo:{
        type:Number,
        required:true,
    },
},

orderItem:{
    Mughlai:{
        price:{
            type:Number,
            required:true,
        },
        Quantity:{
            type:Number,
            required:true,
        }
    },
    Chowmin:{
        price:{
            type:Number,
            required:true,
        },
        Quantity:{
            type:Number,
            required:true,
        }
    },
    ChickenPokora:{
        price:{
            type:Number,
            required:true,
        },
        Quantity:{
            type:Number,
            required:true,
        }
    },
},
user:{
    type:mongoose.Schema.ObjectId,
    ref:"User",
    required:true,
},
paymentMethod:{
    type:String,
    enum:["COD","ONLINE"],
    default:"COD",
},
paymentInfo:{
    type:mongoose.Schema.ObjectId,
    ref:"Payment",
},
paidAt:{
type:Date,
},
ItemsPrice:{
    type:Number,
    default:0,
},
ShippingPrice:{
    type:Number,
    default:30,
},
TaxPrice:{
    type:Number,
    default:0,
},
TotalPrice:{
    type:Number,
    default:0,
},
orderStatus:{
    type:String,
    enum:["preparing","Shipped","Delivered"],
    default:"preparing",
},
DeliveredAt:{
    type:Date,
    
},
CreatedAt:{
    type:Date,
    default:Date.now,
},
})

export const Order=mongoose.model("Order",schema)